name: beast_physical
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase és Google csomagok frissítve a legújabb stabil verziókra
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1

  pedometer: ^4.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutterfire_cli: ^1.0.0 # Frissítve a javasolt verzióra

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ikon-logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
